---
- name: Install application dependencies
  hosts: all
  become: true
  tasks:
  - name: Install Ruby and Bundler
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - ruby-full
        - ruby-bundler
        - build-essential
